spring.application.name=boot11

spring.web.error.whitelabel.enabled=false
spring.web.error.include-exception=true
spring.web.error.include-message=on-param
spring.web.error.include-stacktrace=on-param
spring.web.error.include-binding-errors=on-param