USE PRODUCT;

DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(
	NUM INT PRIMARY KEY AUTO_INCREMENT,
    DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP EVENT IF EXISTS INSERT_EVENT;
CREATE EVENT INSERT_EVENT
ON SCHEDULE EVERY 10 SECOND
STARTS '2024-07-25 12:45:00'
DO
	INSERT INTO TEST() VALUES();

SELECT * FROM TEST;

# 이벤트 스케줄러 확인
SELECT * FROM information_schema.EVENTS;

# 이벤트 스케줄러 상태 확인
SHOW VARIABLES LIKE 'event%';

# 이벤트 스커줄러 상태 변경
SET GLOBAL EVENT_SCHEDULER = ON; # ON OR OFF